### ISSUE TITLE
Trouble using the API with Golang

### ISSUE THREAD

**Issue by falsechicken** [Podcastindex-org/example-code#2]
I am having some issues trying to use the API with Golang. I tried out the C# example and got it working but I am getting an empty response when I try to replicate the example with Go. I was hoping to get this working and contribute some example code. Anyone with maybe more experience with Go can chime in and find out what I am doing wrong? Thanks! 

Code: [https://gist.github.com/falsechicken/c2c0c9b07ebc3ed870c0adfa0442eb07](https://gist.github.com/falsechicken/c2c0c9b07ebc3ed870c0adfa0442eb07)

**Comment by falsechicken** [comment]
Figured it out! Needed to use EncodeToString from the hex package on the sha byte array. Must have missed that when adapting the C# example to Go.

**Comment by podcastindex** [comment]
That should be more clear in the documentation now.  The hex part was a trip up for some.
